# Generated by Django 2.0.12 on 2020-07-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_auto_20200705_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='path',
            field=models.CharField(max_length=999, unique=True),
        ),
    ]
