# Generated by Django 2.0.12 on 2020-07-05 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0003_auto_20200705_0246'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('path', 'parent')},
        ),
    ]
